#' Tools for reading and manipulating Avida data sets
#'
#' \code{avidaR} is an R package for working with data sets generated by the
#' \href{http://avida.devosoft.org/}{Avida} digital evolution platform.
#' 
#' @docType package
#' @name avidaR
#' @import stringr

NULL
